### ISSUE TITLE
Bundle install error

### ISSUE THREAD

**Issue by biologistbrian** [glassechidna/zxing_cpp.rb#5]
Hi, I'm getting this error on bundle

Installing zxing_cpp 0.1.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/brianwatson/.rvm/gems/ruby-2.4.2/gems/zxing_cpp-0.1.1/ext/zxing
/Users/brianwatson/.rvm/rubies/ruby-2.4.2/bin/ruby -r
./siteconf20180726-89062-18o88sr.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/brianwatson/.rvm/rubies/ruby-2.4.2/bin/$(RUBY_BASE_NAME)
extconf.rb:6:in `rescue in <main>': zxing_cpp.rb installation requires cmake
(RuntimeError)
	from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
/Users/brianwatson/.rvm/gems/ruby-2.4.2/gems/zxing_cpp-0.1.1 for inspection.
Results logged to
/Users/brianwatson/.rvm/gems/ruby-2.4.2/extensions/x86_64-darwin-16/2.4.0/zxing_cpp-0.1.1/gem_make.out

An error occurred while installing zxing_cpp (0.1.1), and Bundler
cannot continue.
Make sure that `gem install zxing_cpp -v '0.1.1'` succeeds before bundling.

In Gemfile:
  zxing_cpp

Any thoughts?

**Comment by biologistbrian** [comment]
SORRY.  I didn't read the fine print.  I didn't have cmake installed!
