### ISSUE TITLE
No such file or directory - identify -version (Errno::ENOENT)

### ISSUE THREAD

**Issue by vishless** [glassechidna/zxing_cpp.rb#7]
Trying to build zxing_cpp in Windows 10 with  Ruby+Devkit 2.5.7-1 (x64).
Have ImageMagick and cmake installed.

Here is the error log:

```
C:\Users\viprasant>gem install zxing_cpp
Fetching: rmagick-2.16.0.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing zxing_cpp:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rmagick-2.16.0/ext/RMagick
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20210805-8068-19feoe6.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:141:in ``': No such file or directory - identify -version (Errno::ENOENT)
        from extconf.rb:141:in `configure_compile_options'
        from extconf.rb:16:in `initialize'
        from extconf.rb:548:in `new'
        from extconf.rb:548:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rmagick-2.16.0 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rmagick-2.16.0/gem_make.out
```

The error is occuring at extconf.rb:141 
```
`identify -version` =~ /Version: ImageMagick (\d+\.\d+\.\d+)-+\d+ /`
```

Is identify a program that I need to have?

**Comment by vishless** [comment]
Solved at https://github.com/rmagick/rmagick/issues/1291
